name: Behave Tests

on:
  push:
    branches:
      - main  # Run on push to main branc
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome  # Use a Selenium standalone image with Chrome
        ports:
          - 4444:4444  # Expose the port for Selenium WebDriver

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use Python 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run Behave tests
        run: |
          cd .\testinng\
          behave # Run Behave tests
